use_frameworks!

platform :ios, '10.0'

target 'JMEpubReader_Example' do
  pod 'JMEpubReader', :path => '../'

  target 'JMEpubReader_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
